-- ============================================================
-- FILE: 03_projects.sql
-- PURPOSE: Survey projects — core entity of the entire platform.
-- DEPENDS ON: 02_profiles.sql, 01_enums.sql
-- ROLLBACK: DROP TABLE IF EXISTS projects CASCADE;
-- ============================================================

CREATE TABLE IF NOT EXISTS projects (
  -- Identity
  id                      TEXT PRIMARY KEY,  -- Format: PRJ-YYMM-NNN (e.g. PRJ-2606-001)
  name                    TEXT NOT NULL,

  -- Client Information
  client_name             TEXT NOT NULL,
  client_contact          TEXT,
  client_address          TEXT,

  -- Site Details
  site_type               TEXT,
  site_coordinates        TEXT,
  services                TEXT[] DEFAULT '{}',
  survey_requirements     TEXT,
  description             TEXT,

  -- Workflow State
  status                  TEXT NOT NULL DEFAULT 'lead',
  priority                TEXT DEFAULT 'medium',

  -- Project Controls
  requirement_checklist   JSONB DEFAULT '{
    "timeline_confirmed": false,
    "budget_discussed": false,
    "site_images_received": false,
    "client_requirements_verified": false,
    "measurements_confirmed": false,
    "satbara_uploaded": false
  }',

  -- Dates
  target_completion_date  TIMESTAMPTZ,
  follow_up_date          TIMESTAMPTZ,

  -- Freeze / Lock Controls
  is_frozen               BOOLEAN NOT NULL DEFAULT FALSE,
  freeze_reason           TEXT,
  frozen_at               TIMESTAMPTZ,
  frozen_by               UUID REFERENCES profiles(id) ON DELETE SET NULL,

  -- CAD Escalation Bypass
  bypass_active           BOOLEAN NOT NULL DEFAULT FALSE,

  -- Archival
  satisfaction_score      INTEGER CHECK (satisfaction_score BETWEEN 1 AND 10),
  archival_note           TEXT,

  -- Ownership
  created_by              UUID REFERENCES profiles(id) ON DELETE SET NULL,

  -- Timestamps
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at              TIMESTAMPTZ
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_projects_status       ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_created_by   ON projects(created_by);
CREATE INDEX IF NOT EXISTS idx_projects_deleted_at   ON projects(deleted_at);
CREATE INDEX IF NOT EXISTS idx_projects_priority     ON projects(priority);
CREATE INDEX IF NOT EXISTS idx_projects_is_frozen    ON projects(is_frozen);
CREATE INDEX IF NOT EXISTS idx_projects_created_at   ON projects(created_at DESC);

-- Comments
COMMENT ON TABLE projects IS 'Survey/engineering project records. ID format: PRJ-YYMM-NNN.';
COMMENT ON COLUMN projects.id IS 'Human-readable sequential ID. Generated by get_next_project_id() function.';
COMMENT ON COLUMN projects.status IS 'Current workflow stage. Drives the entire lifecycle state machine.';
COMMENT ON COLUMN projects.is_frozen IS 'If true, all operational work is blocked until outstanding payments are cleared.';
COMMENT ON COLUMN projects.bypass_active IS 'Admin/Engineer can bypass 3-revision CAD escalation hold.';
COMMENT ON COLUMN projects.requirement_checklist IS 'JSONB checklist for pre-quotation requirement gathering.';
