-- 20260719000056_extended_payroll_snapshots.sql

ALTER TABLE payroll_snapshots
ADD COLUMN IF NOT EXISTS basic_salary NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS hra NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS allowance NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gross_salary NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS esi NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS professional_tax NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS income_tax NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS other_deductions NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_deductions NUMERIC(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS net_salary NUMERIC(12, 2) DEFAULT 0;
